### ISSUE TITLE
I cant install restless

### ISSUE THREAD

**Issue by CheyenneForbes** [Corvusoft/restless#15]
I cant install restless, I cloned, I didnt edit anything, after I run `./restless/build/all.sh` I get this error:
```
/home/www/_github/restless/dependency/protocol/test/integration/source/http_frame_builder/is_malformed.cpp:26: FAILED:
  REQUIRE( builder->is_malformed( ) == false )
with expansion:
  true == false

===============================================================================
test cases:  6 |  5 passed | 1 failed
assertions: 32 | 31 passed | 1 failed



92% tests passed, 2 tests failed out of 24

Total Test time (real) =   0.17 sec

The following tests FAILED:
         21 - http_frame_builder_assemble_integration_test_suite (Failed)
         24 - http_frame_builder_is_malformed_integration_test_suite (Failed)
Errors while running CTest
make: *** [test] Error 8

```

**Comment by CheyenneForbes** [comment]
fixed after upgrading from ubuntu 14 to 16 and installing gcc/g++ 7

**Comment by gazzyt** [comment]
I have the same issue. It seems to be caused by [this bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71500#c20). So that explains why upgrading gcc fixed it for you. I'm on Debian GNU/Linux 9 (stretch) and not sure how I'd upgrade to g++7

**Comment by CheyenneForbes** [comment]
Add `https://wiki.debian.org/DebianExperimental` to your /etc/apt/sources.list

Then run

```
apt-get update
apt-get -t experimental install gcc-7
```

**Comment by gazzyt** [comment]
Thanks for the reply. I followed that link and saw that I could also get Debian testing/buster by editing the same file. On the assumption that testing is more stable than experimental I did that, got GCC-8 and restless builds fine.
