### ISSUE TITLE
optional way to make function calls synchronous

### ISSUE THREAD

**Issue by CheyenneForbes** [Corvusoft/restless#18]
In the project I'm working on I use restless but I'm having issues sending "transfer-encoding: chunked" requests because the terminating "0\r\n\r\n" gets delivered before the data. The code is intended to feed uploaded files to the file server in chunks as they come in to the webserver. Could we have an async method for the functions? eg. `void Session::yield( const Bytes data  );`

**Comment by ben-crowhurst** [comment]
Restless is designed for async requests only.

**Comment by CheyenneForbes** [comment]
I realized, thats why I was asking if you could add a way to do synchronous calls... look at my use case above

**Comment by CheyenneForbes** [comment]
Plus i believe if there was a way to do synchronous calls restless would work in restbed callbacks... I think the segfault is due to the `restless::Request` object being "deleted" before `session->send(` uses it, the segfault comes when `session->send(` is called

**Comment by CheyenneForbes** [comment]
Any updates?

**Comment by CheyenneForbes** [comment]
I accepted that its best for it to stay how it is, I changed the code which now captures a callback then call it 
```
//send transfer-encoding: chunked header
session->send( request, [ do_yield_with_data ]( auto session, auto response, auto status ){
    if(status == std::error_code()){
         if(response->get_status_code() == 200){
           //recursively send chunks
           do_yield_with_data();
        }
    }
    return status;
});
```
